# Generated by Django 5.2.17 on 2026-10-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('candidate', 'Candidate'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('invalid', 'Invalid'), ('review_required', 'Review required'), ('retry_wait', 'Retry wait'), ('preparing', 'Preparing'), ('ready', 'Ready')], db_index=True, default='candidate', max_length=20)),
                ('preparation_state', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('artwork_state', models.CharField(choices=[('not_provided', 'Not provided'), ('available', 'Validated; pending embed'), ('embedded', 'Embedded'), ('unsupported', 'Unsupported for format'), ('invalid', 'Invalid artwork')], default='not_provided', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('retry_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_outcome', models.CharField(blank=True, max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=1000)),
                ('candidate_path', models.CharField(blank=True, max_length=1024)),
                ('prepared_path', models.CharField(blank=True, max_length=1024)),
                ('artwork_path', models.CharField(blank=True, max_length=1024)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expected_duration_seconds', models.FloatField(blank=True, null=True)),
                ('observed_facts', models.JSONField(blank=True, default=dict)),
                ('duration_comparison', models.JSONField(blank=True, default=dict)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('preparation_report', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('quality_rank', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_candidates_created', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_candidates', to='releases.canonicalrelease')),
                ('source_match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_candidates', to='releases.sourcematch')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_candidates', to='releases.track')),
            ],
            options={'ordering': ('-created_at', 'pk')},
        ),
        migrations.CreateModel(
            name='MediaAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='media_pipeline.mediacandidate')),
            ],
            options={'ordering': ('-occurred_at', '-pk')},
        ),
        migrations.CreateModel(
            name='MediaAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('retry_wait', 'Retry wait'), ('invalid', 'Invalid'), ('review_required', 'Review required')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='media_pipeline.mediacandidate')),
            ],
            options={'ordering': ('-started_at', '-pk')},
        ),
        migrations.AddIndex(model_name='mediacandidate', index=models.Index(fields=['track', 'state'], name='media_cand_track_state_idx')),
        migrations.AddConstraint(model_name='mediacandidate', constraint=models.UniqueConstraint(condition=~models.Q(('provider', 'manual')), fields=('track', 'source_match', 'provider'), name='media_candidate_identity_uniq')),
    ]
