# Generated by Django 5.2.17 on 2026-10-02 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('lp', 'LP'), ('ep', 'EP')], max_length=12)),
                ('edition', models.CharField(default='original', max_length=32)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('identified', 'Identified'), ('review_required', 'Review required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='identified', max_length=20)),
                ('identity_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='releases.canonicalrelease')),
            ],
            options={'ordering': ('title', 'pk')},
        ),
        migrations.CreateModel(
            name='ReleaseCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_credits', to='sources.artist')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_credits', to='releases.canonicalrelease')),
            ],
            options={'ordering': ('position', 'pk')},
        ),
        migrations.AddField(model_name='canonicalrelease', name='credited_artists', field=models.ManyToManyField(related_name='canonical_releases', through='releases.ReleaseCredit', to='sources.artist')),
        migrations.CreateModel(
            name='SourceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('matching_method', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('matched', 'Matched'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected'), ('review_required', 'Review required')], max_length=20)),
                ('admin_decision', models.CharField(blank=True, max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_match_decisions', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_matches', to='releases.canonicalrelease')),
                ('source_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity_match', to='sources.sourceitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('low_confidence', 'Low confidence'), ('artist_mismatch', 'Artist mismatch'), ('possible_duplicate', 'Possible duplicate'), ('edition', 'Edition ambiguity'), ('collection_type', 'Collection type'), ('invalid_source', 'Invalid source metadata'), ('manual', 'Manual review')], max_length=24)),
                ('reason', models.CharField(max_length=500)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected'), ('requeued', 'Requeued for review')], default='open', max_length=16)),
                ('resolution', models.CharField(blank=True, max_length=1000)),
                ('admin_action', models.CharField(blank=True, choices=[('', '—'), ('approve', 'Approve'), ('reject', 'Reject'), ('correct', 'Correct'), ('requeue', 'Requeue for review')], default='', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_review_decisions', to=settings.AUTH_USER_MODEL)),
                ('resolved_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_resolutions', to='releases.canonicalrelease')),
                ('source_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_item', to='sources.sourceitem')),
                ('source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='releases.sourcematch')),
            ],
            options={'ordering': ('state', '-created_at')},
        ),
        migrations.CreateModel(
            name='IdentityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_audit_events', to='sources.sourceitem')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='releases.reviewitem')),
                ('source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='releases.sourcematch')),
            ],
            options={'ordering': ('-occurred_at',)},
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('official_title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('identity_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.CharField(default='original', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='releases.track')),
            ],
            options={'ordering': ('official_title', 'pk')},
        ),
        migrations.AddField(model_name='sourcematch', name='track', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_matches', to='releases.track')),
        migrations.AddField(model_name='reviewitem', name='resolved_track', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_resolutions', to='releases.track')),
        migrations.CreateModel(
            name='ReleaseTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prior_single', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_links', to='releases.releasetrack')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_tracks', to='releases.canonicalrelease')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_memberships', to='releases.track')),
            ],
            options={'ordering': ('position', 'pk')},
        ),
        migrations.CreateModel(
            name='ProcessingQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('retry_wait', 'Retry wait'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_queue_items', to='releases.canonicalrelease')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_queue_items', to='releases.track')),
            ],
            options={'ordering': ('due_at', 'pk')},
        ),
        migrations.CreateModel(
            name='TrackCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_credits', to='sources.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_credits', to='releases.track')),
            ],
            options={'ordering': ('position', 'pk')},
        ),
        migrations.AddField(model_name='track', name='credited_artists', field=models.ManyToManyField(related_name='canonical_tracks', through='releases.TrackCredit', to='sources.artist')),
        migrations.AddConstraint(model_name='releasecredit', constraint=models.UniqueConstraint(fields=('release', 'artist'), name='release_artist_credit_uniq')),
        migrations.AddIndex(model_name='sourcematch', index=models.Index(fields=['state', 'confidence'], name='source_match_state_conf_idx')),
        migrations.AddConstraint(model_name='sourcematch', constraint=models.CheckConstraint(condition=models.Q(('track__isnull', True), ('release__isnull', False), _connector='OR'), name='source_match_track_has_release')),
        migrations.AddIndex(model_name='reviewitem', index=models.Index(fields=['state', 'category'], name='review_state_category_idx')),
        migrations.AddConstraint(model_name='reviewitem', constraint=models.CheckConstraint(condition=models.Q(('resolved_track__isnull', True), ('resolved_release__isnull', False), _connector='OR'), name='review_track_has_release')),
        migrations.AddConstraint(model_name='releasetrack', constraint=models.UniqueConstraint(fields=('release', 'track'), name='release_track_pair_uniq')),
        migrations.AddConstraint(model_name='releasetrack', constraint=models.UniqueConstraint(fields=('release', 'position'), name='release_track_position_uniq')),
        migrations.AddConstraint(model_name='releasetrack', constraint=models.CheckConstraint(condition=models.Q(('prior_single__isnull', True), models.Q(('pk', models.F('prior_single_id')), _negated=True), _connector='OR'), name='release_track_not_own_prior')),
        migrations.AddIndex(model_name='processingqueueitem', index=models.Index(fields=['state', 'due_at'], name='processing_queue_due_idx')),
        migrations.AddConstraint(model_name='processingqueueitem', constraint=models.CheckConstraint(condition=models.Q(('release__isnull', False), ('track__isnull', False), _connector='OR'), name='queue_item_has_canonical_target')),
        migrations.AddConstraint(model_name='processingqueueitem', constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('track',), name='queue_track_target_uniq')),
        migrations.AddConstraint(model_name='processingqueueitem', constraint=models.UniqueConstraint(condition=models.Q(('release__isnull', False), ('track__isnull', True)), fields=('release',), name='queue_release_target_uniq')),
        migrations.AddConstraint(model_name='trackcredit', constraint=models.UniqueConstraint(fields=('track', 'artist'), name='track_artist_credit_uniq')),
    ]
