# Generated by Django 5.2.17 on 2026-10-05 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_pipeline', '0001_initial'),
        ('publication', '0003_alter_publication_kind'),
        ('releases', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='production', max_length=20, unique=True)),
                ('paused', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreshProviderBackoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True)),
                ('due_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FreshDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(db_index=True, default='review', max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('evidence', models.JSONField(default=dict)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('processing_state', models.CharField(db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='releases.canonicalrelease')),
                ('source_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sources.sourceitem')),
            ],
        ),
        migrations.CreateModel(
            name='FreshTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_id', models.CharField(max_length=22)),
                ('position', models.PositiveSmallIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media_pipeline.mediacandidate')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='releases.freshdispatch')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publication.publication')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='releases.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dispatch', 'position'), name='fresh_track_position_once')],
            },
        ),
    ]
