# Generated by Django 5.2.17 on 2026-10-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_pipeline', '0001_initial'),
        ('publication', '0003_alter_publication_kind'),
        ('releases', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('target', models.CharField(default='-1004311149640', max_length=100)),
                ('roster', models.JSONField(default=list)),
                ('application_sha', models.CharField(max_length=40)),
                ('paused', models.BooleanField(default=True)),
                ('frozen_at', models.DateTimeField(null=True)),
                ('verification', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_position', models.PositiveSmallIntegerField()),
                ('evidence', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField(null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.artistsource')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='archive_collection.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22)),
                ('metadata', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField()),
                ('state', models.CharField(default='pending', max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('retry_due_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media_pipeline.mediacandidate')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to='archive_collection.collection')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_recordings', to='publication.publication')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='releases.track')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('popular_rank', models.PositiveSmallIntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='archive_collection.recording')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='archive_collection.artistselection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='artistselection',
            constraint=models.UniqueConstraint(fields=('collection', 'source'), name='archive_artist_once'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(fields=('collection', 'spotify_id'), name='archive_recording_once'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('selection', 'number'), name='archive_slot_once'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('number__in', (1, 2))), name='archive_two_slots'),
        ),
    ]
