# Generated by Django 5.2.17 on 2026-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorsettings',
            name='notification_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('test_only', 'Test target only')], default='disabled', max_length=16),
        ),
        migrations.AddField(
            model_name='operatorsettings',
            name='notification_target',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
