# Generated by Django 5.2.17 on 2026-10-02 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_pipeline', '0001_initial'),
        ('releases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.JSONField(default=list)),
                ('overflow', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='waiting_media', max_length=20)),
                ('failed_since', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_sessions', to='releases.canonicalrelease')),
            ],
        ),
        migrations.CreateModel(
            name='CaptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='caption_kind_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('single_audio', 'Single audio'), ('album_intro', 'Album introduction'), ('album_track_audio', 'Album track audio'), ('edition', 'Edition audio'), ('overflow', 'Prior-single overflow'), ('correction', 'Correction reply'), ('notification', 'Admin notification')], max_length=24)),
                ('caption_html', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('published', 'Published'), ('retry_wait', 'Retry wait'), ('uncertain', 'Reconciliation required'), ('review_required', 'Review required'), ('deleted', 'Deleted')], default='pending', max_length=16)),
                ('message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('message_url', models.CharField(blank=True, max_length=300)),
                ('retry_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delete_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publication.albumsession')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='media_pipeline.mediacandidate')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_publications', to='publication.publication')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='releases.canonicalrelease')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publication.captiontemplate')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='releases.track')),
            ],
        ),
        migrations.AddField(
            model_name='albumsession',
            name='intro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='introduced_sessions', to='publication.publication'),
        ),
        migrations.CreateModel(
            name='PublicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=24)),
                ('operation_key', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('pending', 'Pending response'), ('succeeded', 'Succeeded'), ('failed', 'Definitely failed'), ('uncertain', 'Uncertain outcome')], default='pending', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_attempts', to='media_pipeline.mediacandidate')),
                ('previous_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_attempts', to='media_pipeline.mediacandidate')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='publication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='publication.publicationattempt')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='publication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, unique=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('active_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_locks', to='publication.albumsession')),
                ('in_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_leases', to='publication.publicationattempt')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publication.publicationchannel'),
        ),
        migrations.AddField(
            model_name='albumsession',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_sessions', to='publication.publicationchannel'),
        ),
        migrations.CreateModel(
            name='PublicationReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='open', max_length=20)),
                ('decision', models.CharField(blank=True, max_length=24)),
                ('evidence', models.CharField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='publication.publicationattempt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publicationattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('publication',), name='publication_pending_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('channel', 'identity_key'), name='publication_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('channel', 'track'), name='publication_track_uniq'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('channel', 'message_id'), name='publication_message_uniq'),
        ),
        migrations.AddConstraint(
            model_name='albumsession',
            constraint=models.UniqueConstraint(fields=('channel', 'release'), name='album_channel_release_uniq'),
        ),
    ]
