# Generated by Django 5.2.17 on 2026-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_captiontemplate_previewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='kind',
            field=models.CharField(choices=[('single_audio', 'Single audio'), ('archive_audio', 'Archive audio'), ('album_intro', 'Album introduction'), ('album_track_audio', 'Album track audio'), ('edition', 'Edition audio'), ('overflow', 'Prior-single overflow'), ('correction', 'Correction reply'), ('notification', 'Admin notification')], max_length=24),
        ),
    ]
