# Generated by Django 5.2.17 on 2026-10-02 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("official_name", models.CharField(max_length=200, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("official_name",)},
        ),
        migrations.CreateModel(
            name="ArtistSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(choices=[("soundcloud", "SoundCloud"), ("spotify", "Spotify")], max_length=20)),
                ("native_profile_id", models.CharField(blank=True, max_length=160)),
                ("canonical_url", models.URLField(blank=True, max_length=500)),
                ("enabled", models.BooleanField(default=False)),
                ("verification", models.CharField(choices=[("unverified", "Unverified"), ("verified", "Verified"), ("unavailable", "Unavailable")], default="unverified", max_length=20)),
                ("baseline_started_at", models.DateTimeField(blank=True, null=True)),
                ("baseline_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("next_poll_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=1000)),
                ("poll_interval_seconds", models.PositiveIntegerField(default=90)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="sources.artist")),
            ],
            options={"ordering": ("artist__official_name", "platform")},
        ),
        migrations.CreateModel(
            name="BaselineRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("running", "Running"), ("complete", "Complete"), ("failed", "Failed")], default="running", max_length=16)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=1000)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="baseline_runs", to="sources.artistsource")),
            ],
            options={"ordering": ("-started_at",)},
        ),
        migrations.CreateModel(
            name="SourceAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=40)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("artist", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="sources.artist")),
                ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="sources.artistsource")),
            ],
            options={"ordering": ("-occurred_at",)},
        ),
        migrations.CreateModel(
            name="SourceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(choices=[("soundcloud", "SoundCloud"), ("spotify", "Spotify")], max_length=20)),
                ("native_item_id", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("canonical_url", models.URLField(blank=True, max_length=1000)),
                ("source_release_at", models.DateTimeField(blank=True, null=True)),
                ("first_observed_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("sanitized_raw_data", models.JSONField(blank=True, default=dict)),
                ("from_baseline", models.BooleanField(default=False)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="sources.artistsource")),
            ],
            options={"ordering": ("-first_observed_at",)},
        ),
        migrations.AddIndex(
            model_name="artistsource",
            index=models.Index(fields=["platform", "enabled", "verification", "next_poll_at"], name="source_due_poll_idx"),
        ),
        migrations.AddConstraint(
            model_name="artistsource",
            constraint=models.UniqueConstraint(fields=("artist", "platform"), name="source_artist_platform_uniq"),
        ),
        migrations.AddConstraint(
            model_name="sourceitem",
            constraint=models.UniqueConstraint(fields=("platform", "native_item_id"), name="source_item_platform_native_uniq"),
        ),
    ]
